CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   BIGINT auto_increment,
    GENRE_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID   BIGINT auto_increment,
    AUTHOR_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKS
(
    BOOK_ID   BIGINT auto_increment,
    BOOK_NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    foreign key (AUTHOR_ID) references AUTHORS (AUTHOR_ID) ON UPDATE CASCADE,
    foreign key (GENRE_ID) references GENRES (GENRE_ID) ON UPDATE CASCADE
);

CREATE TABLE COMMENTS
(
    COMMENT_ID   BIGINT auto_increment,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID      BIGINT,
    foreign key (BOOK_ID) references BOOKS (BOOK_ID) ON DELETE CASCADE
);