CREATE TABLE GENRES (
    GENRE_ID SERIAL PRIMARY KEY,
    GENRE_NAME VARCHAR(255)
);

CREATE TABLE AUTHORS (
    AUTHOR_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME VARCHAR(255)
);

CREATE TABLE BOOKS (
    BOOK_ID SERIAL PRIMARY KEY,
    BOOK_NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT,
    foreign key (AUTHOR_ID) references AUTHORS(AUTHOR_ID),
    foreign key (GENRE_ID) references GENRES(GENRE_ID)
);

CREATE TABLE COMMENTS (
    COMMENT_ID SERIAL PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID BIGINT,
    foreign key (BOOK_ID) references BOOKS(BOOK_ID)
);