CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL ,
    FIRST_NAME VARCHAR(255) NOT NULL ,
    LAST_NAME VARCHAR(255) NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL ,
    ROLE VARCHAR(20) default 'USER',
    STATUS VARCHAR(20) default 'ACTIVE'
);
